version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:14-alpine
    container_name: spa-postgres
    environment:
      POSTGRES_DB: spa_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spa-network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: spa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spa-network
    restart: unless-stopped

  # 后端API服务器（包含数据库初始化）
  backend:
    image: node:18-alpine
    container_name: spa-backend
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/bringup113/SPASYS.git /tmp/spa &&
        cp -r /tmp/spa/server/* . &&
        rm -rf /tmp/spa &&
        npm install --only=production &&
        echo '等待数据库启动...' &&
        sleep 15 &&
        echo '初始化数据库...' &&
        node init-db.js &&
        echo '启动服务器...' &&
        npm start
      "
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=spa_system
      - DB_PASSWORD=password
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - spa-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # 前端应用
  frontend:
    image: node:18-alpine
    container_name: spa-frontend
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/bringup113/SPASYS.git . &&
        npm install &&
        npm run dev -- --host 0.0.0.0
      "
    environment:
      - VITE_API_URL=/api
    ports:
      - "5173:5173"
    networks:
      - spa-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  spa-network:
    driver: bridge